import pool from './db.js';
import jwt from 'jsonwebtoken';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ message: 'Method Not Allowed' });

  // 1. Authenticate the User
  const token = req.headers.authorization?.split(' ')[1];
  if (!token) return res.status(401).json({ error: 'Unauthorized' });

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    const userId = decoded.user_id;

    // 2. Destructure inputs for tblinventory
    const { brand_id, weight_grams, purchase_price, purchase_date } = req.body;

    // 3. Insert into tblinventory
    // Note: UUID is generated by the DB default as per your schema
    const [result] = await pool.execute(
      `INSERT INTO tblinventory (user_id, brand, weight_grams, purchase_price, purchase_date) 
       VALUES (?, ?, ?, ?, ?)`,
      [userId, brand_id, weight_grams, purchase_price, purchase_date || new Date()]
    );

    return res.status(200).json({ 
      success: true, 
      message: 'Gold recorded successfully', 
      inventory_id: result.insertId 
    });

  } catch (error) {
    console.error(error);
    return res.status(403).json({ error: 'Invalid token or Database error' });
  }
}